### ISSUE TITLE
No longer able to serve an image

### ISSUE THREAD

**Issue by afonit** [voila-dashboards/voila#1044]
In Voila `0.2.16` I used to serve little images I would use in various ways.
In Voila '0.3.0' this no longer works, I get `500: Internal Server Error`.

For example, the url would be:
https://voila.name.com/voila/render/static/awareness/calendar_icon.svg

In the directory voila starts from there is a folder called made called `static` with some folders and logos/svg's in it.

I would embed that into notebooks using:
STATIC_LOCATION = 'https://voila.name.com/voila/render/static/awareness/'
Then I would build out the address based on conditions and embed that in a vdom.helpers.img wrapper.

I could build things such as this:
![image](https://user-images.githubusercontent.com/1798497/145879122-c6dfbf7c-391a-4c88-bb15-eaa3e538e26c.png)

But after upgrading to 0.3.0 all the logos don't show up.
looking at the logs when I load the voila pages I get:
```bash
sudo journalctl -u voila -f
```

```
Dec 13 19:38:33 prod-066998 voila[4770]: Traceback (most recent call last):
Dec 13 19:38:33 prod-066998 voila[4770]:   File "/home/ubuntu/miniconda3/envs/data_analysis_lab/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
Dec 13 19:38:33 prod-066998 voila[4770]:     result = await result
Dec 13 19:38:33 prod-066998 voila[4770]:   File "/home/ubuntu/miniconda3/envs/data_analysis_lab/lib/python3.9/site-packages/voila/handler.py", line 150, in get
Dec 13 19:38:33 prod-066998 voila[4770]:     kernel_name=gen.notebook.metadata.kernelspec.name,
Dec 13 19:38:33 prod-066998 voila[4770]: AttributeError: 'NoneType' object has no attribute 'metadata'
Dec 13 19:38:33 prod-066998 voila[4770]: ERROR:tornado.access:500 GET /voila/render/static/awareness/calendar_icon.svg (::1) 4.56ms
```

I just downgraded back to 0.2.16 and everything works again.

I checked the [support documentation](https://voila.readthedocs.io/) and the [release notes](https://github.com/voila-dashboards/voila/releases), as far as I can tell this was unexpected and might be a bug?

**Comment by trungleduc** [comment]
Hi @afonit,
In `0.3.0` , `Voila` will detect the kernel name from the metadata of the notebook, and since you are trying to serve your svg files with the URL `.../voila/render/...`, `Voila` consider the requested file is a notebook and will try to get the kernel name from your SVG file, which leads to the error.

If you set the [static files whitelist ](https://voila.readthedocs.io/en/latest/customize.html#serving-static-files) to  contain `*.svg`, i think your files will be available at URL https://voila.name.com/voila/files/static/awareness/calendar_icon.svg

**Comment by afonit** [comment]
@trungleduc , thank you for pointing out what happened.
I have not yet been able to get it to work with that configuration, but I assume it is an issue on my side so I will mark this as closed.

Thank you again for the insight and help.

**Comment by afonit** [comment]
@trungleduc, perhaps passing that parameter is related to this issue which was never resolved:
https://github.com/voila-dashboards/voila/issues/813

That issue is basically, in the docs it says:
https://voila.readthedocs.io/en/stable/customize.html#hiding-output-and-code-cells-based-on-cell-tags
once should be able to:
```
voila --TagRemovePreprocessor.remove_all_outputs_tags='{"hide"}'
```

But for many including myself, we have to do:
```
--TagRemovePreprocessor.remove_cell_tags hide --TagRemovePreprocessor.remove_cell_tags something
```

As you can see the ' and the " and the { have to be eliminated and the --Tag.. has to be written twice.

**Comment by trungleduc** [comment]
For the complicated settings, I would suggest creating a file named `voila.json`  in the directory where you start `voila` to define your parameters.

For example, the following file will allow you to serve your media files with the URL `.../voila/files/static/awareness/...`

```json
{
    "VoilaConfiguration": {
        "file_whitelist": [
            ".*\\.(png|jpg|gif|svg|mp4|avi|ogg)"
        ]
    }
}
```

**Comment by afonit** [comment]
That worked perfectly - thank you for the guidance.

**Comment by tilusnet** [comment]
Hi.

It seems I am having the same problem, only that I need to load/serve `.html` files inside the notebook.
I run Voila as part of jupyter lab.

I created a `voila.json` file as suggested, but it doesn't get acknowledged. 
Where exactly should it go when I run `jupyter lab`?

Here's my config:

Error:
```
[E 2022-01-22 16:12:15.760 ServerApp] Uncaught exception GET /voila/render/gmail-reloaded/emails_df.html (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/voila/render/gmail-reloaded/emails_df.html', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/tilushq/opt/miniconda3/envs/jupyter/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/home/tilushq/opt/miniconda3/envs/jupyter/lib/python3.7/site-packages/voila/handler.py", line 150, in get
        kernel_name=gen.notebook.metadata.kernelspec.name,
    AttributeError: 'NoneType' object has no attribute 'metadata'
```

I started `jupyter lab` in directory \<X\> and I created a `<X>/voila.json` with:
```
{
    "VoilaConfiguration": {
        "file_whitelist": [
            ".*\\.(png|jpg|gif|svg|mp4|avi|ogg|html|js)"
        ]
    }
}
```

What am I missing?

**Comment by tilusnet** [comment]
I just also tried the documented 

```
voila mydir --VoilaConfiguration.file_whitelist="['.*\.(html)']"
```

it doesn't work either.

I'm using voila 0.3.0.

**Comment by afonit** [comment]
@tilusnet ,
Just a thought -
you wrote:
```
I run Voila as part of jupyter lab.
```
Does that mean you are using the voila jupyter lab extension, eg) you are in jupyterlab and have a notebook open, then you are clicking on the voila icon in the jupyterlab toolbar?

If so, as far as I know, that launches voila on that notebook without any configuration options picked up.  The configuration options are only applied when launching voila itself as shown in your second example.

In your second example, since you have created the `voila.json` in that directory already - have you tried just starting voila there (without the command line parameter you passed in the second example)?

I have not tried the html option, but if you post a small reproducible I could try it on my end and see if it works.

**Comment by tilusnet** [comment]
Hi @afonit,
Thanks for replying.

Yes, originally I ran Voila with the jupyterlab/notebook toolbar. I actually tried both in Jupyterlab 3 and Jupyter Notebook, with the same results.

And I can now confirm that running as standalone as `voila .` in the directory with a `voila.json` having the content 
```json
{
    "VoilaConfiguration": {
        "file_whitelist": [
            ".*\\.(png|jpg|gif|svg|mp4|avi|ogg|html|js)"
        ]
    }
}
```
also generates a 500 status with:
```
ERROR:tornado.access:500 GET /voila/render/emails_df.html (127.0.0.1) 11.12ms
ERROR:tornado.application:Uncaught exception GET /voila/render/emails_df.html (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8866', method='GET', uri='/voila/render/emails_df.html', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/tilushq/opt/miniconda3/envs/jupyter/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/home/tilushq/opt/miniconda3/envs/jupyter/lib/python3.7/site-packages/voila/handler.py", line 150, in get
    kernel_name=gen.notebook.metadata.kernelspec.name,
AttributeError: 'NoneType' object has no attribute 'metadata'
ERROR:tornado.access:500 GET /voila/render/emails_df.html (127.0.0.1) 8.40ms
```

**Comment by trungleduc** [comment]
hello @tilusnet, you should access your static files via `.../voila/files/static/...` URL and not `/voila/render/...` as in your error log.

**Comment by tilusnet** [comment]
Hi @trungleduc ,

Voila generates the `/voila/render/...` path automatically, I have no control over that.
The `/voila/files/static/` paths seem to [refer to template files](https://voila.readthedocs.io/en/stable/customize.html#adding-your-own-static-files)? My html files do not belong to templates.

My typical use case is loading html files inside IPython `IFrame` objects to render user interfaces with `ipywidgets`. IFrame objects load html source files.
While this works in Jupyter, Voila doesn't like loading the html files.

**Comment by trungleduc** [comment]
It does seem related to https://github.com/voila-dashboards/voila/issues/1049, can you provide a minimal code to reproduce the bug?

**Comment by tilusnet** [comment]
Here it is:

```python
with open('hello.html', 'w') as fw:
    _ = fw.write('<body><h1>Hello World!</h1></body>')
    
from IPython.display import display, IFrame

my_html_widget = IFrame(
    src='hello.html',
    width=300,
    height=100
)

import ipywidgets as w

widget_output = w.Output()
with widget_output:
    display(my_html_widget)

widget_output
```

![image](https://user-images.githubusercontent.com/705606/150695046-d48932ee-d22e-4c57-be85-70c36ecd8273.png)

**Comment by tilusnet** [comment]
If you think my issue is unrelated to this https://github.com/voila-dashboards/voila/issues/1044, I can file a new ticket.
Thanks in advance for your assistance.

**Comment by tilusnet** [comment]
FYI, I created https://github.com/voila-dashboards/voila/issues/1071 for this issue.
